var group__EM__Library =
[
    [ "ACMP", "group__ACMP.html", "group__ACMP" ],
    [ "ADC", "group__ADC.html", "group__ADC" ],
    [ "BITBAND", "group__BITBAND.html", "group__BITBAND" ],
    [ "BUS", "group__BUS.html", "group__BUS" ],
    [ "CHIP", "group__CHIP.html", "group__CHIP" ],
    [ "CMU", "group__CMU.html", "group__CMU" ],
    [ "COMMON", "group__COMMON.html", "group__COMMON" ],
    [ "CRYOTIMER", "group__CRYOTIMER.html", "group__CRYOTIMER" ],
    [ "CRYPTO", "group__CRYPTO.html", "group__CRYPTO" ],
    [ "DBG", "group__DBG.html", "group__DBG" ],
    [ "EMU", "group__EMU.html", "group__EMU" ],
    [ "GPIO", "group__GPIO.html", "group__GPIO" ],
    [ "I2C", "group__I2C.html", "group__I2C" ],
    [ "IDAC", "group__IDAC.html", "group__IDAC" ],
    [ "INT", "group__INT.html", "group__INT" ],
    [ "LDMA", "group__LDMA.html", "group__LDMA" ],
    [ "LETIMER", "group__LETIMER.html", "group__LETIMER" ],
    [ "LEUART", "group__LEUART.html", "group__LEUART" ],
    [ "MPU", "group__MPU.html", "group__MPU" ],
    [ "MSC", "group__MSC.html", "group__MSC" ],
    [ "PCNT", "group__PCNT.html", "group__PCNT" ],
    [ "PRS", "group__PRS.html", "group__PRS" ],
    [ "RMU", "group__RMU.html", "group__RMU" ],
    [ "RTCC", "group__RTCC.html", "group__RTCC" ],
    [ "SYSTEM", "group__SYSTEM.html", "group__SYSTEM" ],
    [ "TIMER", "group__TIMER.html", "group__TIMER" ],
    [ "USART", "group__USART.html", "group__USART" ],
    [ "VERSION", "group__VERSION.html", "group__VERSION" ],
    [ "WDOG", "group__WDOG.html", "group__WDOG" ]
];