EFM32 Giant Gecko Software Documentation: CapSense
CapSense
Drivers
Functions
uint8_t CAPLESENSE_getSegmentChannel (uint8_t capSegment)
Get the channelValue for a sensor segment.
uint32_t CAPLESENSE_getVal (uint8_t channel)
Get the current channelValue for a channel.
uint32_t CAPLESENSE_getNormalizedVal (uint8_t channel)
Get the current normalized channelValue for a channel.
int32_t CAPLESENSE_getSliderPosition (void)
Get the position of the slider.
void CAPLESENSE_Init (bool sleep)
Initializes the capacative sense system without LESENSE.
void CAPLESENSE_setupLESENSE (bool sleep)
Setup the LESENSE for capavitive sensing.
void CAPLESENSE_setupCallbacks (void(*scanCb)(void), void(*chCb)(void))
LESENSE callback setup.
void CAPLESENSE_Sleep (void)
Send the capacative sense system to sleep mode.
uint32_t CAPSENSE_getVal (uint8_t channel)
Get the current channelValue for a channel.
uint32_t CAPSENSE_getNormalizedVal (uint8_t channel)
Get the current normalized channelValue for a channel.
bool CAPSENSE_getPressed (uint8_t channel)
Get the state of the Gecko Button.
int32_t CAPSENSE_getSliderPosition (void)
Get the position of the slider.
void CAPSENSE_Sense (void)
This function iterates through all the capsensors and reads and initiates a reading. Uses EM1 while waiting for the result from each sensor.
void CAPSENSE_Init (void)
Initializes the capacitive sense system.
Detailed Description
Function Documentation
uint8_t CAPLESENSE_getSegmentChannel (uint8_t capSegment)
Parameters
capSegment
Returns
channel
Definition at line 411 of file caplesense.c.
uint32_t CAPLESENSE_getVal (uint8_t channel)
Parameters
channel The channel.
Returns
The channelValue.
Definition at line 440 of file caplesense.c.
References channelValues.
uint32_t CAPLESENSE_getNormalizedVal (uint8_t channel)
Parameters
channel The channel.
Returns
The channel value in range (0-256).
Definition at line 450 of file caplesense.c.
References channelMaxValues, and channelValues.
int32_t CAPLESENSE_getSliderPosition (void)
Returns
The position of the slider if it can be determined, -1 otherwise.
Definition at line 463 of file caplesense.c.
References channelMaxValues, and channelValues.
void CAPLESENSE_Init (bool sleep)
Parameters
sleep If true, go into sleep mode.
Definition at line 531 of file caplesense.c.
References CAPLESENSE_setupACMP(), CAPLESENSE_setupCMU(), CAPLESENSE_setupGPIO(), CAPLESENSE_setupLESENSE(), INT_Disable(), and INT_Enable().
void CAPLESENSE_setupLESENSE (bool sleep)
Parameters
sleep If true, go into sleep mode.
Definition at line 174 of file caplesense.c.
References LESENSE_Init_TypeDef::coreCtrl, LESENSE, LESENSE_ChannelAllConfig(), LESENSE_ChannelThresSet(), LESENSE_ClkDivSet(), LESENSE_Init(), LESENSE_IntClear(), LESENSE_IntDisable(), LESENSE_IntEnable(), LESENSE_IRQn, LESENSE_ResultBufferClear(), LESENSE_ScanFreqSet(), LESENSE_ScanResultDataBufferGet(), LESENSE_ScanStart(), LESENSE_ScanStop(), LESENSE_STATUS_BUFHALFFULL, LESENSE_STATUS_SCANACTIVE, LESENSE_StatusGet(), lesenseACMPModeMuxThres, lesenseBiasModeDutyCycle, lesenseBufTrigHalf, lesenseClkDiv_1, lesenseClkDiv_8, lesenseClkLF, lesenseDACConvModeDisable, lesenseDACIfData, lesenseDACOutModeDisable, lesenseDACRefBandGap, lesenseDecInputSensorSt, lesenseDMAWakeUpDisable, lesensePRSCh0, lesensePRSCh1, lesensePRSCh2, lesensePRSCh3, lesenseScanConfDirMap, lesenseScanStartPeriodic, lesenseWarmupModeNormal, and LESENSE_CoreCtrlDesc_TypeDef::scanStart.
Referenced by CAPLESENSE_Init().
void CAPLESENSE_setupCallbacks (void(*)(void) scanCb, void(*)(void) chCb)
Parameters
scanCb Scan callback
chCb Channel callback
Definition at line 342 of file caplesense.c.
References lesenseChCb, and lesenseScanCb.
uint32_t CAPSENSE_getVal (uint8_t channel)
Parameters
channel The channel.
Returns
The channelValue.
Definition at line 121 of file capsense.c.
References channelValues.
uint32_t CAPSENSE_getNormalizedVal (uint8_t channel)
Parameters
channel The channel.
Returns
The channel value in range (0-256).
Definition at line 131 of file capsense.c.
References channelMaxValues, and channelValues.
bool CAPSENSE_getPressed (uint8_t channel)
Parameters
channel The channel.
Returns
true if the button is "pressed" false otherwise.
Definition at line 143 of file capsense.c.
References channelMaxValues, and channelValues.
int32_t CAPSENSE_getSliderPosition (void)
Returns
The position of the slider if it can be determined, -1 otherwise.
Definition at line 164 of file capsense.c.
References channelMaxValues, and channelValues.
void CAPSENSE_Init (void)
Capacitive sensing uses two timers: TIMER0 and TIMER1 as well as ACMP. ACMP is set up in cap-sense (oscillator mode). TIMER1 counts the number of pulses generated by ACMP_CAPSENSE. When TIMER0 expires it generates an interrupt. The number of pulses counted by TIMER1 is then stored in channelValues
Definition at line 290 of file capsense.c.
References ACMP_CAPSENSE_INIT_DEFAULT, ACMP_CapsenseInit(), CMU, CMU_ClockEnable(), cmuClock_HFPER, cmuClock_PRS, cmuClock_TIMER0, cmuClock_TIMER1, PRS, PRS_CH_CTRL_EDSEL_POSEDGE, TIMER0, TIMER0_IRQn, TIMER1, TIMER_CC_CTRL_ICEDGE_BOTH, TIMER_CC_CTRL_ICEVCTRL_RISING, TIMER_CC_CTRL_INSEL_PRS, TIMER_CC_CTRL_MODE_INPUTCAPTURE, TIMER_CC_CTRL_PRSSEL_PRSCH0, TIMER_CTRL_CLKSEL_CC1, TIMER_CTRL_PRESC_DIV1024, TIMER_CTRL_PRESC_DIV512, and TIMER_IEN_OF.