Silicon Labs EFM32 emlib Peripheral Library: BITBAND
BITBAND
[EM_Library]
BITBAND Peripheral API.
Functions
__STATIC_INLINE void BITBAND_Peripheral (volatile uint32_t *addr, uint32_t bit, uint32_t val)
Perform bit-band operation on peripheral memory location.
__STATIC_INLINE uint32_t BITBAND_PeripheralRead (volatile uint32_t *addr, uint32_t bit)
Perform a read operation on the peripheral bit-band memory location.
__STATIC_INLINE void BITBAND_SRAM (uint32_t *addr, uint32_t bit, uint32_t val)
Perform bit-band operation on SRAM memory location.
__STATIC_INLINE uint32_t BITBAND_SRAMRead (uint32_t *addr, uint32_t bit)
Read a single bit from the SRAM bit-band alias region.
Detailed Description
BITBAND Peripheral API.
Function Documentation
__STATIC_INLINE void BITBAND_Peripheral (volatile uint32_t * addr, uint32_t bit, uint32_t val)
Perform bit-band operation on peripheral memory location.
Bit-banding provides atomic read-modify-write cycle for single bit modification. Please refer to the reference manual for further details about bit-banding.
Note:
This function is only atomic on cores which fully support bitbanding.
Parameters:
[in] addr Peripheral address location to modify bit in.
[in] bit Bit position to modify, 0-31.
[in] val Value to set bit to, 0 or 1.
Definition at line 71 of file em_bitband.h.
Referenced by ACMP_CapsenseInit(), ACMP_Init(), BURTC_CounterReset(), BURTC_Enable(), BURTC_FreezeEnable(), BURTC_Powerdown(), BURTC_Reset(), CMU_ClockDivSet(), CMU_ClockEnable(), CMU_ClockSelectSet(), CMU_PCNTClockExternalSet(), DAC_Enable(), DAC_Init(), DMA_CfgChannel(), EBI_AltMapEnable(), EBI_BankAddressTimingConfig(), EBI_BankByteLaneEnable(), EBI_BankEnable(), EBI_BankPolaritySet(), EBI_BankReadTimingConfig(), EBI_BankWriteTimingConfig(), EBI_ChipSelectEnable(), EBI_Init(), EBI_PolaritySet(), EMU_EM2Block(), EMU_EM2UnBlock(), GPIO_DbgSWDClkEnable(), GPIO_DbgSWDIOEnable(), GPIO_IntConfig(), I2C_Enable(), I2C_Init(), LCD_SegmentSet(), LESENSE_AltExConfig(), LESENSE_ChannelConfig(), LESENSE_ChannelEnable(), PCNT_CounterReset(), PCNT_Init(), PCNT_PRSInputEnable(), PCNT_Reset(), RMU_ResetCauseClear(), RMU_ResetControl(), RTC_Enable(), WDOG_Enable(), WDOG_Init(), and WDOG_Lock().
__STATIC_INLINE uint32_t BITBAND_PeripheralRead (volatile uint32_t * addr, uint32_t bit)
Perform a read operation on the peripheral bit-band memory location.
This function reads a single bit from the peripheral bit-band alias region. Bit-banding provides atomic read-modify-write cycle for single bit modification. Please refer to the reference manual for further details about bit-banding.
Parameters:
[in] addr Peripheral address location to read.
[in] bit Bit position to read, 0-31.
Returns:
Value of the requested bit.
Definition at line 105 of file em_bitband.h.
Referenced by BURTC_Reset().
__STATIC_INLINE void BITBAND_SRAM (uint32_t * addr, uint32_t bit, uint32_t val)
Perform bit-band operation on SRAM memory location.
Bit-banding provides atomic read-modify-write cycle for single bit modification. Please refer to the reference manual for further details about bit-banding.
Note:
This function is only atomic on cores which fully support bitbanding.
Parameters:
[in] addr SRAM address location to modify bit in.
[in] bit Bit position to modify, 0-31.
[in] val Value to set bit to, 0 or 1.
Definition at line 137 of file em_bitband.h.
__STATIC_INLINE uint32_t BITBAND_SRAMRead (uint32_t * addr, uint32_t bit)
Read a single bit from the SRAM bit-band alias region.
This function reads a single bit from the SRAM bit-band alias region. Bit-banding provides atomic read-modify-write cycle for single bit modification. Please refer to the reference manual for further details about bit-banding.
Parameters:
[in] addr SRAM address location to modify bit in.
[in] bit Bit position to modify, 0-31.
Returns:
Value of the requested bit.
Definition at line 169 of file em_bitband.h.