EFM32 Pearl Gecko Software Documentation: RTCC
RTCC
EM_Library
Real Time Counter (RTCC) Peripheral API
.
Data Structures
struct RTCC_Init_TypeDef
struct RTCC_CCChConf_TypeDef
Macros
#define RTCC_INIT_DEFAULT
#define RTCC_CH_INIT_COMPARE_DEFAULT
#define RTCC_CH_INIT_CAPTURE_DEFAULT
#define RTCC_CH_VALID(ch) ((ch) < 3)
Enumerations
enum RTCC_CntMode_TypeDef {
rtccCntModeNormal = _RTCC_CTRL_CNTTICK_PRESC,
rtccCntModeCalendar = _RTCC_CTRL_CNTTICK_CCV0MATCH
}
enum RTCC_CntPresc_TypeDef {
rtccCntPresc_1 = _RTCC_CTRL_CNTPRESC_DIV1,
rtccCntPresc_2 = _RTCC_CTRL_CNTPRESC_DIV2,
rtccCntPresc_4 = _RTCC_CTRL_CNTPRESC_DIV4,
rtccCntPresc_8 = _RTCC_CTRL_CNTPRESC_DIV8,
rtccCntPresc_16 = _RTCC_CTRL_CNTPRESC_DIV16,
rtccCntPresc_32 = _RTCC_CTRL_CNTPRESC_DIV32,
rtccCntPresc_64 = _RTCC_CTRL_CNTPRESC_DIV64,
rtccCntPresc_128 = _RTCC_CTRL_CNTPRESC_DIV128,
rtccCntPresc_256 = _RTCC_CTRL_CNTPRESC_DIV256,
rtccCntPresc_512 = _RTCC_CTRL_CNTPRESC_DIV512,
rtccCntPresc_1024 = _RTCC_CTRL_CNTPRESC_DIV1024,
rtccCntPresc_2048 = _RTCC_CTRL_CNTPRESC_DIV2048,
rtccCntPresc_4096 = _RTCC_CTRL_CNTPRESC_DIV4096,
rtccCntPresc_8192 = _RTCC_CTRL_CNTPRESC_DIV8192,
rtccCntPresc_16384 = _RTCC_CTRL_CNTPRESC_DIV16384,
rtccCntPresc_32768 = _RTCC_CTRL_CNTPRESC_DIV32768
}
enum RTCC_PrescMode_TypeDef {
rtccCntTickPresc = _RTCC_CTRL_CNTTICK_PRESC,
rtccCntTickCCV0Match = _RTCC_CTRL_CNTTICK_CCV0MATCH
}
enum RTCC_CapComChMode_TypeDef {
rtccCapComChModeOff = _RTCC_CC_CTRL_MODE_OFF,
rtccCapComChModeCapture = _RTCC_CC_CTRL_MODE_INPUTCAPTURE,
rtccCapComChModeCompare = _RTCC_CC_CTRL_MODE_OUTPUTCOMPARE
}
enum RTCC_CompMatchOutAction_TypeDef {
rtccCompMatchOutActionPulse = _RTCC_CC_CTRL_CMOA_PULSE,
rtccCompMatchOutActionToggle = _RTCC_CC_CTRL_CMOA_TOGGLE,
rtccCompMatchOutActionClear = _RTCC_CC_CTRL_CMOA_CLEAR,
rtccCompMatchOutActionSet = _RTCC_CC_CTRL_CMOA_SET
}
enum RTCC_PRSSel_TypeDef {
rtccPRSCh0 = _RTCC_CC_CTRL_PRSSEL_PRSCH0,
rtccPRSCh1 = _RTCC_CC_CTRL_PRSSEL_PRSCH1,
rtccPRSCh2 = _RTCC_CC_CTRL_PRSSEL_PRSCH2,
rtccPRSCh3 = _RTCC_CC_CTRL_PRSSEL_PRSCH3,
rtccPRSCh4 = _RTCC_CC_CTRL_PRSSEL_PRSCH4,
rtccPRSCh5 = _RTCC_CC_CTRL_PRSSEL_PRSCH5,
rtccPRSCh6 = _RTCC_CC_CTRL_PRSSEL_PRSCH6,
rtccPRSCh7 = _RTCC_CC_CTRL_PRSSEL_PRSCH7,
rtccPRSCh8 = _RTCC_CC_CTRL_PRSSEL_PRSCH8,
rtccPRSCh9 = _RTCC_CC_CTRL_PRSSEL_PRSCH9,
rtccPRSCh10 = _RTCC_CC_CTRL_PRSSEL_PRSCH10,
rtccPRSCh11 = _RTCC_CC_CTRL_PRSSEL_PRSCH11
}
enum RTCC_InEdgeSel_TypeDef {
rtccInEdgeRising = _RTCC_CC_CTRL_ICEDGE_RISING,
rtccInEdgeFalling = _RTCC_CC_CTRL_ICEDGE_FALLING,
rtccInEdgeBoth = _RTCC_CC_CTRL_ICEDGE_BOTH,
rtccInEdgeNone = _RTCC_CC_CTRL_ICEDGE_NONE
}
enum RTCC_CompBase_TypeDef {
rtccCompBaseCnt = _RTCC_CC_CTRL_COMPBASE_CNT,
rtccCompBasePreCnt = _RTCC_CC_CTRL_COMPBASE_PRECNT
}
enum RTCC_DayCompareMode_TypeDef {
rtccDayCompareModeMonth = _RTCC_CC_CTRL_DAYCC_MONTH,
rtccDayCompareModeWeek = _RTCC_CC_CTRL_DAYCC_WEEK
}
Functions
__STATIC_INLINE uint32_t RTCC_ChannelCCVGet (int ch)
Get RTCC capture/compare register value (CCV) for selected channel.
__STATIC_INLINE void RTCC_ChannelCCVSet (int ch, uint32_t value)
Set RTCC capture/compare register value (CCV) for selected channel.
__STATIC_INLINE uint32_t RTCC_ChannelDateGet (int ch)
Get the calendar DATE register content for selected channel.
__STATIC_INLINE void RTCC_ChannelDateSet (int ch, uint32_t date)
Set the calendar DATE register for selected channel.
void RTCC_ChannelInit (int ch, RTCC_CCChConf_TypeDef const *confPtr)
Configure the selected capture/compare channel of the RTCC.
__STATIC_INLINE uint32_t RTCC_ChannelTimeGet (int ch)
Get the calendar TIME register content for selected channel.
__STATIC_INLINE void RTCC_ChannelTimeSet (int ch, uint32_t time)
Set the calendar TIME register for selected channel.
__STATIC_INLINE uint32_t RTCC_CombinedCounterGet (void)
Get the combined CNT/PRECNT register content.
__STATIC_INLINE uint32_t RTCC_CounterGet (void)
Get RTCC counter value.
__STATIC_INLINE void RTCC_CounterSet (uint32_t value)
Set RTCC CNT counter.
__STATIC_INLINE uint32_t RTCC_DateGet (void)
Get DATE register value.
__STATIC_INLINE void RTCC_DateSet (uint32_t date)
Set RTCC DATE register.
__STATIC_INLINE void RTCC_EM4WakeupEnable (bool enable)
Enable/disable EM4 wakeup capability.
void RTCC_Enable (bool enable)
Enable/disable RTCC.
void RTCC_Init (const RTCC_Init_TypeDef *init)
Initialize RTCC.
__STATIC_INLINE void RTCC_IntClear (uint32_t flags)
Clear one or more pending RTCC interrupts.
__STATIC_INLINE void RTCC_IntDisable (uint32_t flags)
Disable one or more RTCC interrupts.
__STATIC_INLINE void RTCC_IntEnable (uint32_t flags)
Enable one or more RTCC interrupts.
__STATIC_INLINE uint32_t RTCC_IntGet (void)
Get pending RTCC interrupt flags.
__STATIC_INLINE uint32_t RTCC_IntGetEnabled (void)
Get enabled and pending RTCC interrupt flags.
__STATIC_INLINE void RTCC_IntSet (uint32_t flags)
Set one or more pending RTCC interrupts from SW.
__STATIC_INLINE void RTCC_Lock (void)
Lock RTCC registers.
__STATIC_INLINE uint32_t RTCC_PreCounterGet (void)
Get RTCC pre-counter value.
__STATIC_INLINE void RTCC_PreCounterSet (uint32_t preCntVal)
Set RTCC pre-counter value.
void RTCC_Reset (void)
Restore RTCC to its reset state.
__STATIC_INLINE void RTCC_RetentionRamPowerDown (void)
Power down the retention ram.
void RTCC_StatusClear (void)
Clear STATUS register.
__STATIC_INLINE uint32_t RTCC_StatusGet (void)
Get STATUS register value.
__STATIC_INLINE uint32_t RTCC_TimeGet (void)
Get TIME register value.
__STATIC_INLINE void RTCC_TimeSet (uint32_t time)
Set RTCC TIME register.
__STATIC_INLINE void RTCC_Unlock (void)
Unlock RTCC registers.
Detailed Description
Macro Definition Documentation
#define RTCC_INIT_DEFAULT
Value:
{                                                                           \
  true,     /* Start counting when init done.                           */  \
  false,    /* Disable RTCC during debug halt.                          */  \
  false,    /* Disable precounter wrap on ch. 0 CCV value.              */  \
  false,    /* Disable counter wrap on ch. 1 CCV value.                 */  \
  rtccCntPresc_32, /* 977 us per tick.                                  */  \
  rtccCntTickPresc, /* Counter increments according to prescaler value. */  \
  false,    /* No RTCC oscillator failure detection.                    */  \
  rtccCntModeNormal, /* Normal RTCC mode.                               */  \
  false,    /* No leap year correction.                                 */  \
}
Default RTCC init structure.
Definition at line 260 of file em_rtcc.h.
Referenced by UDELAY_Calibrate().
#define RTCC_CH_INIT_COMPARE_DEFAULT
Value:
{                                                                           \
  rtccCapComChModeCompare,     /* Select output compare mode.     */        \
  rtccCompMatchOutActionPulse, /* Create pulse on compare match.  */        \
  rtccPRSCh0,                  /* PRS channel 0 (not used).       */        \
  rtccInEdgeNone,              /* No edge detection.              */        \
  rtccCompBaseCnt,             /* Counter comparison base.        */        \
  0,                           /* No compare mask bits set.       */        \
  rtccDayCompareModeMonth      /* Don't care */                             \
}
Default RTCC channel output compare init structure.
Definition at line 275 of file em_rtcc.h.
#define RTCC_CH_INIT_CAPTURE_DEFAULT
Value:
{                                                                           \
  rtccCapComChModeCapture,     /* Select input capture mode.      */        \
  rtccCompMatchOutActionPulse, /* Create pulse on capture.        */        \
  rtccPRSCh0,                  /* PRS channel 0.                  */        \
  rtccInEdgeRising,            /* Rising edge detection.          */        \
  rtccCompBaseCnt,             /* Don't care.                     */        \
  0,                           /* Don't care.                     */        \
  rtccDayCompareModeMonth      /* Don't care                      */        \
}
Default RTCC channel input capture init structure.
Definition at line 287 of file em_rtcc.h.
#define RTCC_CH_VALID (ch) ((ch) < 3)
Validation of valid RTCC channel for assert statements.
Definition at line 299 of file em_rtcc.h.
Referenced by RTCC_ChannelCCVGet(), RTCC_ChannelCCVSet(), RTCC_ChannelDateGet(), RTCC_ChannelDateSet(), RTCC_ChannelInit(), RTCC_ChannelTimeGet(), and RTCC_ChannelTimeSet().
Enumeration Type Documentation
enum RTCC_CntMode_TypeDef
Operational mode of the counter.
Enumerator
rtccCntModeNormal
Normal counter mode. The counter is incremented by 1 for each tick.
rtccCntModeCalendar
Calendar mode. Refer to the RTCC chapter of the Reference Manual for more details on the calendar mode.
Definition at line 61 of file em_rtcc.h.
enum RTCC_CntPresc_TypeDef
Counter prescaler selection.
Enumerator
rtccCntPresc_1
Divide clock by 1.
rtccCntPresc_2
Divide clock by 2.
rtccCntPresc_4
Divide clock by 4.
rtccCntPresc_8
Divide clock by 8.
rtccCntPresc_16
Divide clock by 16.
rtccCntPresc_32
Divide clock by 32.
rtccCntPresc_64
Divide clock by 64.
rtccCntPresc_128
Divide clock by 128.
rtccCntPresc_256
Divide clock by 256.
rtccCntPresc_512
Divide clock by 512.
rtccCntPresc_1024
Divide clock by 1024.
rtccCntPresc_2048
Divide clock by 2048.
rtccCntPresc_4096
Divide clock by 4096.
rtccCntPresc_8192
Divide clock by 8192.
rtccCntPresc_16384
Divide clock by 16384.
rtccCntPresc_32768
Divide clock by 32768.
Definition at line 72 of file em_rtcc.h.
enum RTCC_PrescMode_TypeDef
Prescaler mode of the RTCC counter.
Enumerator
rtccCntTickPresc
CNT register ticks according to the prescaler value.
rtccCntTickCCV0Match
CNT register ticks when PRECNT matches the 15 least significant bits of ch. 0 CCV register.
Definition at line 94 of file em_rtcc.h.
enum RTCC_CapComChMode_TypeDef
Capture/Compare channel mode.
Enumerator
rtccCapComChModeOff
Capture/Compare channel turned off.
rtccCapComChModeCapture
Capture mode.
rtccCapComChModeCompare
Compare mode.
Definition at line 106 of file em_rtcc.h.
enum RTCC_CompMatchOutAction_TypeDef
Compare match output action mode.
Enumerator
rtccCompMatchOutActionPulse
Generate a pulse.
rtccCompMatchOutActionToggle
Toggle output.
rtccCompMatchOutActionClear
Clear output.
rtccCompMatchOutActionSet
Set output.
Definition at line 114 of file em_rtcc.h.
enum RTCC_PRSSel_TypeDef
PRS input sources.
Enumerator
rtccPRSCh0
PRS channel 0.
rtccPRSCh1
PRS channel 1.
rtccPRSCh2
PRS channel 2.
rtccPRSCh3
PRS channel 3.
rtccPRSCh4
PRS channel 4.
rtccPRSCh5
PRS channel 5.
rtccPRSCh6
PRS channel 6.
rtccPRSCh7
PRS channel 7.
rtccPRSCh8
PRS channel 8.
rtccPRSCh9
PRS channel 9.
rtccPRSCh10
PRS channel 10.
rtccPRSCh11
PRS channel 11.
Definition at line 124 of file em_rtcc.h.
enum RTCC_InEdgeSel_TypeDef
Input edge select.
Enumerator
rtccInEdgeRising
Rising edges detected.
rtccInEdgeFalling
Falling edges detected.
rtccInEdgeBoth
Both edges detected.
rtccInEdgeNone
No edge detection, signal is left as is.
Definition at line 142 of file em_rtcc.h.
enum RTCC_CompBase_TypeDef
Capture/Compare channel compare mode.
Enumerator
rtccCompBaseCnt
CCVx is compared with the CNT register.
rtccCompBasePreCnt
CCVx is compared with a CNT[16:0] and PRECNT[14:0].
Definition at line 152 of file em_rtcc.h.
enum RTCC_DayCompareMode_TypeDef
Day compare mode.
Enumerator
rtccDayCompareModeMonth
Day of month is selected for Capture/Compare.
rtccDayCompareModeWeek
Day of week is selected for Capture/Compare.
Definition at line 162 of file em_rtcc.h.
Function Documentation
__STATIC_INLINE uint32_t RTCC_ChannelCCVGet (int ch)
Parameters
[in] ch Channel selector.
Returns
Capture/compare register value.
Definition at line 315 of file em_rtcc.h.
References RTCC, and RTCC_CH_VALID.
__STATIC_INLINE void RTCC_ChannelCCVSet (int ch, uint32_t value)
Parameters
[in] ch Channel selector.
[in] value CCV value.
Definition at line 331 of file em_rtcc.h.
References RTCC, and RTCC_CH_VALID.
__STATIC_INLINE uint32_t RTCC_ChannelDateGet (int ch)
Parameters
[in] ch Channel selector.
Returns
DATE register value.
Definition at line 347 of file em_rtcc.h.
References RTCC, and RTCC_CH_VALID.
__STATIC_INLINE void RTCC_ChannelDateSet (int ch, uint32_t date)
Parameters
[in] ch Channel selector.
[in] date DATE value.
Definition at line 363 of file em_rtcc.h.
References RTCC, and RTCC_CH_VALID.
void RTCC_ChannelInit (int ch, RTCC_CCChConf_TypeDef const * confPtr)
Use this function to configure a RTCC channel. Select capture/compare mode, match output action, overflow output action and PRS input configuration. Refer to the configuration structure RTCC_CCChConf_TypeDef for more details.
Parameters
[in] ch Channel selector.
[in] confPtr Pointer to configuration structure.
Configure the selected capture/compare channel.
Definition at line 77 of file em_rtcc.c.
References _RTCC_CC_CTRL_CMOA_SHIFT, _RTCC_CC_CTRL_COMPBASE_SHIFT, _RTCC_CC_CTRL_COMPMASK_MASK, _RTCC_CC_CTRL_COMPMASK_SHIFT, _RTCC_CC_CTRL_DAYCC_SHIFT, _RTCC_CC_CTRL_ICEDGE_SHIFT, _RTCC_CC_CTRL_MODE_SHIFT, _RTCC_CC_CTRL_PRSSEL_SHIFT, RTCC_CCChConf_TypeDef::chMode, RTCC_CCChConf_TypeDef::compBase, RTCC_CCChConf_TypeDef::compMask, RTCC_CCChConf_TypeDef::compMatchOutAction, RTCC_CCChConf_TypeDef::dayCompMode, RTCC_CCChConf_TypeDef::inputEdgeSel, RTCC_CCChConf_TypeDef::prsSel, RTCC, and RTCC_CH_VALID.
Referenced by RTCDRV_Init().
__STATIC_INLINE uint32_t RTCC_ChannelTimeGet (int ch)
Parameters
[in] ch Channel selector.
Returns
TIME register value.
Definition at line 381 of file em_rtcc.h.
References RTCC, and RTCC_CH_VALID.
__STATIC_INLINE void RTCC_ChannelTimeSet (int ch, uint32_t time)
Parameters
[in] ch Channel selector.
[in] time TIME value.
Definition at line 397 of file em_rtcc.h.
References RTCC, and RTCC_CH_VALID.
__STATIC_INLINE uint32_t RTCC_CombinedCounterGet (void)
Returns
CNT/PRECNT register value.
Definition at line 410 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE uint32_t RTCC_CounterGet (void)
Returns
Current RTCC counter value.
Definition at line 422 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_CounterSet (uint32_t value)
Parameters
[in] value CNT value.
Definition at line 434 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE uint32_t RTCC_DateGet (void)
Returns
Current DATE register value.
Definition at line 446 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_DateSet (uint32_t date)
Parameters
[in] date DATE value.
Definition at line 458 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_EM4WakeupEnable (bool enable)
Parameters
[in] enable True to enable EM4 wakeup, false to disable.
Definition at line 470 of file em_rtcc.h.
References RTCC, and RTCC_EM4WUEN_EM4WU.
void RTCC_Enable (bool enable)
Parameters
[in] enable True to enable RTCC, false to disable.
Definition at line 101 of file em_rtcc.c.
References _RTCC_CTRL_ENABLE_SHIFT, BUS_RegBitWrite(), and RTCC.
Referenced by RTCDRV_DeInit(), and UDELAY_Calibrate().
void RTCC_Init (const RTCC_Init_TypeDef * init)
Note that the compare values must be set separately with RTCC_CompareSet(). That should probably be done prior to the use of this function if configuring the RTCC to start when initialization is completed.
Parameters
[in] init Pointer to RTCC initialization structure.
Definition at line 119 of file em_rtcc.c.
References _RTCC_CTRL_CCV1TOP_SHIFT, _RTCC_CTRL_CNTMODE_SHIFT, _RTCC_CTRL_CNTPRESC_SHIFT, _RTCC_CTRL_CNTTICK_SHIFT, _RTCC_CTRL_DEBUGRUN_SHIFT, _RTCC_CTRL_ENABLE_SHIFT, _RTCC_CTRL_LYEARCORRDIS_SHIFT, _RTCC_CTRL_OSCFDETEN_SHIFT, _RTCC_CTRL_PRECCV0TOP_SHIFT, RTCC_Init_TypeDef::cntMode, RTCC_Init_TypeDef::cntWrapOnCCV1, RTCC_Init_TypeDef::debugRun, RTCC_Init_TypeDef::disLeapYearCorr, RTCC_Init_TypeDef::enable, RTCC_Init_TypeDef::enaOSCFailDetect, RTCC_Init_TypeDef::precntWrapOnCCV0, RTCC_Init_TypeDef::presc, RTCC_Init_TypeDef::prescMode, and RTCC.
Referenced by RTCDRV_Init(), and UDELAY_Calibrate().
__STATIC_INLINE void RTCC_IntClear (uint32_t flags)
Parameters
[in] flags RTCC interrupt sources to clear. Use a set of interrupt flags OR-ed together to clear multiple interrupt sources.
Definition at line 494 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_IntDisable (uint32_t flags)
Parameters
[in] flags RTCC interrupt sources to disable. Use a set of interrupt flags OR-ed together to disable multiple interrupt.
Definition at line 507 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_IntEnable (uint32_t flags)
Note
Depending on the use, a pending interrupt may already be set prior to enabling the interrupt. Consider using RTCC_IntClear() prior to enabling if such a pending interrupt should be ignored.
Parameters
[in] flags RTCC interrupt sources to enable. Use a set of interrupt flags OR-ed together to set multiple interrupt.
Definition at line 525 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE uint32_t RTCC_IntGet (void)
Note
The event bits are not cleared by the use of this function.
Returns
Pending RTCC interrupt sources. Returns a set of interrupt flags OR-ed together for the interrupt sources set.
Definition at line 541 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE uint32_t RTCC_IntGetEnabled (void)
Useful for handling more interrupt sources in the same interrupt handler.
Returns
Pending and enabled RTCC interrupt sources. Returns a set of interrupt flags OR-ed together for the interrupt sources set.
Definition at line 557 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_IntSet (uint32_t flags)
Parameters
[in] flags RTCC interrupt sources to set to pending. Use a set of interrupt flags (RTCC_IFS_nnn).
Definition at line 575 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_Lock (void)
Note
When RTCC registers are locked, RTCC_CTRL, RTCC_PRECNT, RTCC_CNT, RTCC_TIME, RTCC_DATE, RTCC_IEN, RTCC_POWERDOWN and RTCC_CCx_XXX registers can not be written to.
Definition at line 589 of file em_rtcc.h.
References RTCC, and RTCC_LOCK_LOCKKEY_LOCK.
__STATIC_INLINE uint32_t RTCC_PreCounterGet (void)
Returns
Current RTCC pre-counter value.
Definition at line 601 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_PreCounterSet (uint32_t preCntVal)
Parameters
[in] preCntVal RTCC pre-counter value to be set.
Definition at line 613 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_RetentionRamPowerDown (void)
Note
Once retention ram is powered down, it cannot be powered up again.
Definition at line 627 of file em_rtcc.h.
References RTCC, and RTCC_POWERDOWN_RAM.
__STATIC_INLINE uint32_t RTCC_StatusGet (void)
Returns
Current STATUS register value.
Definition at line 641 of file em_rtcc.h.
References RTCC, and RTCC_SYNCBUSY_CMD.
__STATIC_INLINE uint32_t RTCC_TimeGet (void)
Returns
Current TIME register value.
Definition at line 657 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_TimeSet (uint32_t time)
Parameters
[in] time TIME value.
Definition at line 669 of file em_rtcc.h.
References RTCC.
__STATIC_INLINE void RTCC_Unlock (void)
Note
When RTCC registers are locked, RTCC_CTRL, RTCC_PRECNT, RTCC_CNT, RTCC_TIME, RTCC_DATE, RTCC_IEN, RTCC_POWERDOWN and RTCC_CCx_XXX registers can not be written to.
Definition at line 683 of file em_rtcc.h.
References RTCC, and RTCC_LOCK_LOCKKEY_UNLOCK.
Referenced by RTCC_Reset().