Board Support Package: SegmentLcd
SegmentLcd
[Drivers]
Functions
void SegmentLCD_AllOff (void)
Disable all segments.
void SegmentLCD_AllOn (void)
Enable all segments.
void SegmentLCD_AlphaNumberOff (void)
Turn all segments on alpha characters in display off.
void SegmentLCD_ARing (int anum, int on)
Light up or shut off Ring of Indicators.
void SegmentLCD_Battery (int batteryLevel)
Light up or shut off Battery Indicator.
void SegmentLCD_Disable (void)
Disables LCD controller.
void SegmentLCD_EnergyMode (int em, int on)
Light up or shut off Energy Mode indicator.
void SegmentLCD_Init (bool useBoost)
Segment LCD Initialization routine for EFM32 STK display.
void SegmentLCD_LowerHex (uint32_t num)
Write a hexadecimal number on lower alphanumeric part of Segment LCD display.
void SegmentLCD_LowerNumber (int num)
Write number on lower alphanumeric part of Segment LCD display.
void SegmentLCD_Number (int value)
Write number on numeric part on Segment LCD display.
void SegmentLCD_NumberOff (void)
Turn all segments on numeric digits in display off.
void SegmentLCD_Symbol (lcdSymbol s, int on)
Light up or shut off various symbols on Segment LCD.
void SegmentLCD_UnsignedHex (uint16_t value)
Write hexadecimal number on numeric part on Segment LCD display.
void SegmentLCD_Write (char *string)
Write text on LCD display.
Function Documentation
void SegmentLCD_AllOff (void)
Disable all segments.
Definition at line 253 of file segmentlcd.c.
Referenced by SegmentLCD_Init().
void SegmentLCD_AllOn (void)
Enable all segments.
Definition at line 263 of file segmentlcd.c.
void SegmentLCD_AlphaNumberOff (void)
Turn all segments on alpha characters in display off.
Definition at line 272 of file segmentlcd.c.
Referenced by SegmentLCD_Write().
void SegmentLCD_ARing (int anum, int on)
Light up or shut off Ring of Indicators.
Parameters:
anum "Segment number" on "Ring", range 0 - 7
on Zero is off, non-zero is on
Definition at line 284 of file segmentlcd.c.
References MCU_DISPLAY::ARing, ARING_TypeDef::bit, and ARING_TypeDef::com.
void SegmentLCD_Battery (int batteryLevel)
Light up or shut off Battery Indicator.
Parameters:
batteryLevel Battery Level, 0 to 4 (0 turns all off)
Definition at line 306 of file segmentlcd.c.
References MCU_DISPLAY::Battery, BATTERY_TypeDef::bit, and BATTERY_TypeDef::com.
void SegmentLCD_Disable (void)
Disables LCD controller.
Definition at line 339 of file segmentlcd.c.
void SegmentLCD_EnergyMode (int em, int on)
Light up or shut off Energy Mode indicator.
Parameters:
em Energy Mode numer 0 to 4
on Zero is off, non-zero is on
Definition at line 360 of file segmentlcd.c.
References EM_TypeDef::bit, EM_TypeDef::com, and MCU_DISPLAY::EMode.
void SegmentLCD_Init (bool useBoost)
Segment LCD Initialization routine for EFM32 STK display.
Parameters:
useBoost Set to use voltage boost
Definition at line 382 of file segmentlcd.c.
References SegmentLCD_AllOff().
void SegmentLCD_LowerHex (uint32_t num)
Write a hexadecimal number on lower alphanumeric part of Segment LCD display.
Parameters:
num Hexadecimal number value to put on display, in range 0 to 0x0FFFFFFF
Definition at line 432 of file segmentlcd.c.
References SegmentLCD_Symbol(), and SegmentLCD_Write().
void SegmentLCD_LowerNumber (int num)
Write number on lower alphanumeric part of Segment LCD display.
Parameters:
num Numeric value to put on display, in range -9999999 to +9999999
Definition at line 463 of file segmentlcd.c.
References SegmentLCD_Symbol(), and SegmentLCD_Write().
void SegmentLCD_Number (int value)
Write number on numeric part on Segment LCD display.
Parameters:
value Numeric value to put on display, in range -999 to +9999
Definition at line 503 of file segmentlcd.c.
References NUMBER_TypeDef::bit, NUMBER_TypeDef::com, EFM_Numbers, MCU_DISPLAY::Number, and SegmentLCD_NumberOff().
void SegmentLCD_NumberOff (void)
Turn all segments on numeric digits in display off.
Definition at line 564 of file segmentlcd.c.
Referenced by SegmentLCD_Number(), and SegmentLCD_UnsignedHex().
void SegmentLCD_Symbol (lcdSymbol s, int on)
Light up or shut off various symbols on Segment LCD.
Parameters:
s Which symbol to turn on or off
on Zero is off, non-zero is on
Definition at line 577 of file segmentlcd.c.
Referenced by SegmentLCD_LowerHex(), and SegmentLCD_LowerNumber().
void SegmentLCD_UnsignedHex (uint16_t value)
Write hexadecimal number on numeric part on Segment LCD display.
Parameters:
value Numeric value to put on display, in range 0x0000-0xFFFF
Definition at line 705 of file segmentlcd.c.
References NUMBER_TypeDef::bit, NUMBER_TypeDef::com, EFM_Numbers, MCU_DISPLAY::Number, and SegmentLCD_NumberOff().
void SegmentLCD_Write (char * string)
Write text on LCD display.
Parameters:
string Text string to show on display
Definition at line 749 of file segmentlcd.c.
References CHAR_TypeDef::bit, CHAR_TypeDef::com, EFM_Alphabet, SegmentLCD_AlphaNumberOff(), and MCU_DISPLAY::Text.
Referenced by SegmentLCD_LowerHex(), and SegmentLCD_LowerNumber().