Board Support Package: common/drivers/rtcdrv.c File Reference
rtcdrv.c File Reference
Real Time Counter (RTC) driver, implements simple trigger functionality.
#include <stddef.h>
#include "em_device.h"
#include "em_cmu.h"
#include "em_emu.h"
#include "em_rtc.h"
#include "rtcdrv.h"
Functions
static void DelayCB (void)
Delay RTC callback.
void RTCDRV_Setup (CMU_Select_TypeDef lfaClockSrc, CMU_ClkDiv_TypeDef rtcPrescale)
Setup RTC with selected clock source and prescaler.
void RTCDRV_Delay (uint32_t msec, bool useEM2)
RTC delay function.
void RTC_IRQHandler (void)
RTC Interrupt Handler, invoke callback function if defined.
void RTCDRV_Trigger (uint32_t msec, void(*cb)(void))
RTC trigger enable.
Variables
static void(* rtcCb)(void)
RTC callback.
static uint8_t rtcInitialized = 0
1 if rtc is initialized
static volatile bool rtcDelayComplete
True while CB delay and false while polled delay.
static uint32_t rtcFreq
RTC Frequence.
Detailed Description
Real Time Counter (RTC) driver, implements simple trigger functionality.
Version:
4.0.0
(C) Copyright 2014 Silicon Labs, http://www.silabs.com
This file is licensed under the Silabs License Agreement. See the file "Silabs_License_Agreement.txt" for details. Before using this software for any purpose, you must agree to the terms of that agreement.
Definition in file rtcdrv.c.
Function Documentation
static void DelayCB (void) [static]
Delay RTC callback.
Definition at line 33 of file rtcdrv.c.
References rtcDelayComplete.
Referenced by RTCDRV_Delay().
void RTC_IRQHandler (void)
RTC Interrupt Handler, invoke callback function if defined.
Definition at line 102 of file rtcdrv.c.
References rtcCb.
Variable Documentation
void(* rtcCb)(void) [static]
RTC callback.
Definition at line 25 of file rtcdrv.c.
Referenced by RTC_IRQHandler(), and RTCDRV_Trigger().
volatile bool rtcDelayComplete [static]
True while CB delay and false while polled delay.
Definition at line 27 of file rtcdrv.c.
Referenced by DelayCB(), and RTCDRV_Delay().
uint32_t rtcFreq [static]
RTC Frequence.
32.768 kHz
Definition at line 28 of file rtcdrv.c.
Referenced by RTCDRV_Setup(), and RTCDRV_Trigger().
uint8_t rtcInitialized = 0 [static]
1 if rtc is initialized
Definition at line 26 of file rtcdrv.c.
Referenced by RTCDRV_Setup(), and RTCDRV_Trigger().