Silicon Labs Energy Aware Drivers: ezradiodrv/common/inc/ezradio_hal.h File Reference
ezradio_hal.h File Reference
This file contains EZRadio HAL.
#include "ezradiodrv_config.h"
Functions
void ezradio_hal_GpioInit (GPIOINT_IrqCallbackPtr_t ezradioIrqCallback)
void ezradio_hal_SpiInit (void)
void ezradio_hal_AssertShutdown (void)
void ezradio_hal_DeassertShutdown (void)
void ezradio_hal_ClearNsel (void)
void ezradio_hal_SetNsel (void)
uint8_t ezradio_hal_NirqLevel (void)
void ezradio_hal_SpiWriteByte (uint8_t byteToWrite)
void ezradio_hal_SpiReadByte (uint8_t *readByte)
void ezradio_hal_SpiWriteData (uint8_t byteCount, uint8_t *pData)
void ezradio_hal_SpiReadData (uint8_t byteCount, uint8_t *pData)
Detailed Description
This file contains EZRadio HAL.
Version:
4.0.0
(C) Copyright 2015 Silicon Labs, http://www.silabs.com
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software. 3. This notice may not be removed or altered from any source distribution.
DISCLAIMER OF WARRANTY/LIMITATION OF REMEDIES: Silicon Labs has no obligation to support this Software. Silicon Labs is providing the Software "AS IS", with no express or implied warranties of any kind, including, but not limited to, any implied warranties of merchantability or fitness for any particular purpose or warranties against infringement of any proprietary rights of a third party.
Silicon Labs will not be liable for any consequential, incidental, or special damages, or any other relief, or for any claim by any third party, arising from your use of this Software.
Definition in file ezradio_hal.h.
Function Documentation
void ezradio_hal_AssertShutdown (void)
Asserts SDN pin of the EZRadio device.
Definition at line 127 of file ezradio_hal.c.
Referenced by ezradio_reset().
void ezradio_hal_ClearNsel (void)
Clears nSEL pin of the EZRadio device.
Definition at line 143 of file ezradio_hal.c.
Referenced by ezradio_comm_GetResp(), ezradio_comm_ReadData(), ezradio_comm_SendCmd(), and ezradio_comm_WriteData().
void ezradio_hal_DeassertShutdown (void)
Deasserts SDN pin of the EZRadio device.
Definition at line 135 of file ezradio_hal.c.
Referenced by ezradio_reset().
void ezradio_hal_GpioInit (GPIOINT_IrqCallbackPtr_t ezradioIrqCallback)
Configures the EZRadio GPIO port and pins
Parameters:
radioIrqCallback EZRadio interrupt callback configuration
Definition at line 60 of file ezradio_hal.c.
References GPIOINT_CallbackRegister().
uint8_t ezradio_hal_NirqLevel (void)
Reads nIRQ pin of the EZRadio device.
Returns:
Value of nIRQ pin.
Definition at line 161 of file ezradio_hal.c.
void ezradio_hal_SetNsel (void)
Sets nSEL pin of the EZRadio device.
Definition at line 151 of file ezradio_hal.c.
Referenced by ezradio_comm_GetResp(), ezradio_comm_ReadData(), ezradio_comm_SendCmd(), and ezradio_comm_WriteData().
void ezradio_hal_SpiReadByte (uint8_t * readByte)
Reads a single byte from the EZRadio SPI port.
Parameters:
readByte Read byte.
Definition at line 185 of file ezradio_hal.c.
References SPIDRV_MReceiveB().
Referenced by ezradio_comm_GetResp().
void ezradio_hal_SpiReadData (uint8_t byteCount, uint8_t * pData)
Reads byteCount number of bytes from the EZRadio SPI port.
Parameters:
byteCount Number of bytes to write.
pData Pointer to the byte array.
Definition at line 221 of file ezradio_hal.c.
References SPIDRV_MReceiveB().
Referenced by ezradio_comm_GetResp(), and ezradio_comm_ReadData().
void ezradio_hal_SpiWriteByte (uint8_t byteToWrite)
Writes a single byte to the EZRadio SPI port.
Parameters:
byteToWrite Byte to write.
Definition at line 171 of file ezradio_hal.c.
References SPIDRV_MTransmitB().
Referenced by ezradio_comm_GetResp(), ezradio_comm_ReadData(), and ezradio_comm_WriteData().
void ezradio_hal_SpiWriteData (uint8_t byteCount, uint8_t * pData)
Writes byteCount number of bytes to the EZRadio SPI port.
Parameters:
byteCount Number of bytes to write.
pData Pointer to the byte array.
Definition at line 201 of file ezradio_hal.c.
References SPIDRV_MTransmitB().
Referenced by ezradio_comm_SendCmd(), and ezradio_comm_WriteData().