Silicon Labs Energy Aware Drivers: Direct_Transmit_Plugin
Direct_Transmit_Plugin
[Plugin_System]
Direct transmit plugin, see Plugin System Layer on page EZRADIODRV EzRadio Peripheral Interface driver for detailed documentation.
Data Structures
struct EZRADIODRV_DirectTxHandle_t
EzRadio direct tx plug-in instance initialization and handler structure.
Defines
#define EZRADIODRV_DIRECT_TRANSMIT_PLUGIN_INIT_DEFAULT
Configuration data for EzRadio direct tx plug-in.
Functions
Ecode_t ezradioStartDirectTransmit (EZRADIODRV_Handle_t radioHandle)
Starts direct transmission with the radio configurations from the radioHandle parameter.
Ecode_t ezradioStopDirectTransmit (void)
Stops direct transmission.
Detailed Description
Direct transmit plugin, see Plugin System Layer on page EZRADIODRV EzRadio Peripheral Interface driver for detailed documentation.
Define Documentation
#define EZRADIODRV_DIRECT_TRANSMIT_PLUGIN_INIT_DEFAULT
Value:
{                               /* PN9                              */  \
  0,                            /* Channel                          */  \
},
Configuration data for EzRadio direct tx plug-in.
Definition at line 75 of file ezradio_direct_transmit_plugin.h.
Function Documentation
Ecode_t ezradioStartDirectTransmit (EZRADIODRV_Handle_t radioHandle)
Starts direct transmission with the radio configurations from the radioHandle parameter.
Parameters:
radioHandle Handler of the EzRadio driver instance where channel configuration is set.
Returns:
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 56 of file ezradio_direct_transmit_plugin.c.
References ECODE_EMDRV_EZRADIODRV_ILLEGAL_HANDLE, ECODE_EMDRV_EZRADIODRV_OK, ECODE_EMDRV_EZRADIODRV_TRANSMIT_FAILED, ezradio_get_int_status(), ezradio_request_device_state(), and ezradio_start_tx().
Ecode_t ezradioStopDirectTransmit (void)
Stops direct transmission.
Returns:
ECODE_EMDRV_EZRADIODRV_OK on success. On failure an appropriate EZRADIODRV Ecode_t is returned.
Definition at line 88 of file ezradio_direct_transmit_plugin.c.
References ECODE_EMDRV_EZRADIODRV_OK, and ezradio_change_state().