Silicon Labs Energy Aware Drivers: API_Layer
API_Layer
[EZRADIODRV]
EzRadio API Layer, see Radio API Layer on page EZRADIODRV EzRadio Peripheral Interface driver for detailed documentation.
Enumerations
enum EZRADIO_ConfigRet_t {
EZRADIO_CONFIG_SUCCESS,
EZRADIO_CONFIG_NO_PATCH,
EZRADIO_CONFIG_CTS_TIMEOUT,
EZRADIO_CONFIG_PATCH_FAIL,
EZRADIO_CONFIG_COMMAND_ERROR
}
EZRadio device configuration return values.
Functions
void ezradio_reset (void)
This functions is used to reset the EZRadio device by applying shutdown and releasing it.
void ezradio_power_up (uint8_t boot_options, uint8_t xtal_options, uint32_t xo_freq)
This function is used to initialize after power-up the radio chip.
void ezradio_part_info (ezradio_cmd_reply_t *ezradioReply)
This function sends the PART_INFO command to the radio and receives the answer into ezradioReply union.
void ezradio_start_tx (uint8_t channel, uint8_t condition, uint16_t tx_len)
Sends START_TX command to the radio.
void ezradio_start_rx (uint8_t channel, uint8_t condition, uint16_t rx_len, uint8_t next_state1, uint8_t next_state2, uint8_t next_state3)
Sends START_RX command to the radio.
void ezradio_get_int_status (uint8_t ph_clr_pend, uint8_t modem_clr_pend, uint8_t chip_clr_pend, ezradio_cmd_reply_t *ezradioReply)
Get the Interrupt status/pending flags form the radio and clear flags if requested.
void ezradio_gpio_pin_cfg (uint8_t gpio0, uint8_t gpio1, uint8_t gpio2, uint8_t gpio3, uint8_t nirq, uint8_t sdo, uint8_t gen_config, ezradio_cmd_reply_t *ezradioReply)
Send GPIO pin config command to the radio and reads the answer into ezradioReply union.
void ezradio_set_property (uint8_t group, uint8_t num_props, uint8_t start_prop,...)
Send SET_PROPERTY command to the radio.
void ezradio_change_state (uint8_t next_state1)
Issue a change state command to the radio.
void ezradio_nop (void)
Sends NOP command to the radio.
void ezradio_fifo_info (uint8_t fifo, ezradio_cmd_reply_t *ezradioReply)
Send the FIFO_INFO command to the radio.
void ezradio_write_tx_fifo (uint8_t numbytes, uint8_t *pdata)
The function can be used to load data into TX FIFO.
void ezradio_read_rx_fifo (uint8_t numbytes, uint8_t *prxdata)
Reads the RX FIFO content from the radio.
void ezradio_get_property (uint8_t group, uint8_t num_props, uint8_t start_prop, ezradio_cmd_reply_t *ezradioReply)
Get property values from the radio.
void ezradio_func_info (ezradio_cmd_reply_t *ezradioReply)
Sends the FUNC_INFO command to the radio, then reads the resonse into ezradioReply union.
void ezradio_frr_a_read (uint8_t respByteCount, ezradio_cmd_reply_t *ezradioReply)
Reads the Fast Response Registers starting with A register into ezradioReply union.
void ezradio_frr_b_read (uint8_t respByteCount, ezradio_cmd_reply_t *ezradioReply)
Reads the Fast Response Registers starting with B register into ezradioReply union.
void ezradio_frr_c_read (uint8_t respByteCount, ezradio_cmd_reply_t *ezradioReply)
Reads the Fast Response Registers starting with C register into ezradioReply union.
void ezradio_frr_d_read (uint8_t respByteCount, ezradio_cmd_reply_t *ezradioReply)
Reads the Fast Response Registers starting with D register into ezradioReply union.
void ezradio_request_device_state (ezradio_cmd_reply_t *ezradioReply)
Requests the current state of the device and lists pending TX and RX requests.
void ezradio_read_cmd_buff (ezradio_cmd_reply_t *ezradioReply)
Reads the command buffer.
void ezradio_get_ph_status (uint8_t ph_clr_pend, ezradio_cmd_reply_t *ezradioReply)
Gets the Packet Handler status flags.
void ezradio_get_modem_status (uint8_t modem_clr_pend, ezradio_cmd_reply_t *ezradioReply)
Gets the Modem status flags.
void ezradio_get_chip_status (uint8_t chip_clr_pend, ezradio_cmd_reply_t *ezradioReply)
Gets the Chip status flags.
void ezradio_get_packet_info (uint8_t field_number_mask, uint16_t len, int16_t diff_len, ezradio_cmd_reply_t *ezradioReply)
Receives information from the radio of the current packet.
void ezradio_start_tx_fast (void)
Sends START_TX command ID to the radio with no input parameters.
void ezradio_start_rx_fast (void)
Sends START_RX command ID to the radio with no input parameters.
void ezradio_get_int_status_fast_clear (void)
Clear all Interrupt status/pending flags.
void ezradio_get_int_status_fast_clear_read (ezradio_cmd_reply_t *ezradioReply)
Clear and read all Interrupt status/pending flags.
void ezradio_gpio_pin_cfg_fast (ezradio_cmd_reply_t *ezradioReply)
Reads back current GPIO pin configuration.
void ezradio_get_ph_status_fast_clear (void)
Clear all Packet Handler status flags.
void ezradio_get_ph_status_fast_clear_read (ezradio_cmd_reply_t *ezradioReply)
Clear and read all Packet Handler status flags.
void ezradio_get_modem_status_fast_clear (void)
Clear all Modem status flags.
void ezradio_get_modem_status_fast_clear_read (ezradio_cmd_reply_t *ezradioReply)
Clear and read all Modem status flags.
void ezradio_get_chip_status_fast_clear (void)
Clear all Chip status flags.
void ezradio_get_chip_status_fast_clear_read (ezradio_cmd_reply_t *ezradioReply)
Clear and read all Chip status flags.
void ezradio_fifo_info_fast_reset (uint8_t fifo)
Resets the RX/TX FIFO.
void ezradio_fifo_info_fast_read (ezradio_cmd_reply_t *ezradioReply)
Reads RX/TX FIFO count space.
EZRADIO_ConfigRet_t ezradio_configuration_init (const uint8_t *pSetPropCmd)
This function is used to load all properties and commands with a list of NULL terminated commands.
void ezradio_write_ezconfig_array (uint8_t numBytes, uint8_t *pEzConfigArray)
Writes data byte(s) to the EZConfig array.
void ezradio_ezconfig_check (uint16_t checksum, ezradio_cmd_reply_t *ezradioReply)
Validates the EZConfig array was written correctly.
void ezradio_get_adc_reading (uint8_t adc_en, uint8_t adc_cfg, ezradio_cmd_reply_t *ezradioReply)
Reads the ADC values from the radio into ezradioReply union.
void ezradio_ircal (uint8_t searching_step_size, uint8_t searching_rssi_avg, uint8_t rx_chain_setting1, uint8_t rx_chain_setting2)
Performs image rejection calibration.
void ezradio_ircal_manual (uint8_t ircal_amp, uint8_t ircal_ph, ezradio_cmd_reply_t *ezradioReply)
Image rejection calibration.
void ezradio_tx_hop (uint8_t inte, uint8_t frac2, uint8_t frac1, uint8_t frac0, uint8_t vco_cnt1, uint8_t vco_cnt0, uint8_t pll_settle_time1, uint8_t pll_settle_time0)
While in TX state this will hop to the frequency specified by the parameters.
void ezradio_rx_hop (uint8_t inte, uint8_t frac2, uint8_t frac1, uint8_t frac0, uint8_t vco_cnt1, uint8_t vco_cnt0)
While in RX state this will hop to the frequency specified by the parameters and start searching for a preamble.
Detailed Description
EzRadio API Layer, see Radio API Layer on page EZRADIODRV EzRadio Peripheral Interface driver for detailed documentation.
Enumeration Type Documentation
enum EZRADIO_ConfigRet_t
EZRadio device configuration return values.
Enumerator:
EZRADIO_CONFIG_SUCCESS
Configuration succeded.
EZRADIO_CONFIG_NO_PATCH
No patch is given.
EZRADIO_CONFIG_CTS_TIMEOUT
CTS timeout error during configuration.
EZRADIO_CONFIG_PATCH_FAIL
Patching is failed.
EZRADIO_CONFIG_COMMAND_ERROR
Command error during configuration.
Definition at line 67 of file ezradio_api_lib.h.
Function Documentation
void ezradio_change_state (uint8_t next_state1)
Issue a change state command to the radio.
Parameters:
[in] next_state1 Next state.
Definition at line 291 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
Referenced by ezradioStopDirectReceive(), ezradioStopDirectTransmit(), ezradioStopPn9(), and ezradioStopUnmodulatedCarrier().
EZRADIO_ConfigRet_t ezradio_configuration_init (const uint8_t * pSetPropCmd)
This function is used to load all properties and commands with a list of NULL terminated commands.
Before this function ezradio_reset should be called.
Parameters:
[in] pSetPropCmd Pointer to the configuration array.
Definition at line 52 of file ezradio_api_lib_add.c.
References ezradio_comm_SendCmdGetResp(), EZRADIO_CONFIG_COMMAND_ERROR, EZRADIO_CONFIG_CTS_TIMEOUT, EZRADIO_CONFIG_SUCCESS, ezradio_get_int_status(), ezradio_hal_NirqLevel(), and ezradio_write_ezconfig_array().
Referenced by ezradioInit().
void ezradio_ezconfig_check (uint16_t checksum, ezradio_cmd_reply_t * ezradioReply)
Validates the EZConfig array was written correctly.
Parameters:
[in] checksum Checksum value
[out] ezradioReply Reply structure of the command.
Definition at line 158 of file ezradio_api_lib_add.c.
References ezradio_comm_CtsWentHigh, and ezradio_comm_SendCmdGetResp().
void ezradio_fifo_info (uint8_t fifo, ezradio_cmd_reply_t * ezradioReply)
Send the FIFO_INFO command to the radio.
Optionally resets the TX/RX FIFO. Reads the radio response back into ezradioReply.
Parameters:
[in] fifo RX/TX FIFO reset flags.
[out] ezradioReply Reply structure of the command.
Definition at line 325 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
Referenced by ezradioResetTRxFifo().
void ezradio_fifo_info_fast_read (ezradio_cmd_reply_t * ezradioReply)
Reads RX/TX FIFO count space.
Does NOT reset RX/TX FIFO
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 922 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_fifo_info_fast_reset (uint8_t fifo)
Resets the RX/TX FIFO.
Does not read back anything from TX/RX FIFO
Parameters:
[in] fifo FIFO to be reset.
Definition at line 906 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_frr_a_read (uint8_t respByteCount, ezradio_cmd_reply_t * ezradioReply)
Reads the Fast Response Registers starting with A register into ezradioReply union.
Parameters:
[in] respByteCount Number of Fast Response Registers to be read.
[out] ezradioReply Reply structure of the command.
Definition at line 439 of file ezradio_api_lib.c.
References ezradio_comm_ReadData().
void ezradio_frr_b_read (uint8_t respByteCount, ezradio_cmd_reply_t * ezradioReply)
Reads the Fast Response Registers starting with B register into ezradioReply union.
Parameters:
[in] respByteCount Number of Fast Response Registers to be read.
[out] ezradioReply Reply structure of the command.
Definition at line 461 of file ezradio_api_lib.c.
References ezradio_comm_ReadData().
void ezradio_frr_c_read (uint8_t respByteCount, ezradio_cmd_reply_t * ezradioReply)
Reads the Fast Response Registers starting with C register into ezradioReply union.
Parameters:
[in] respByteCount Number of Fast Response Registers to be read.
[out] ezradioReply Reply structure of the command.
Definition at line 483 of file ezradio_api_lib.c.
References ezradio_comm_ReadData().
void ezradio_frr_d_read (uint8_t respByteCount, ezradio_cmd_reply_t * ezradioReply)
Reads the Fast Response Registers starting with D register into ezradioReply union.
Parameters:
[in] respByteCount Number of Fast Response Registers to be read.
[out] ezradioReply Reply structure of the command.
Definition at line 505 of file ezradio_api_lib.c.
References ezradio_comm_ReadData().
void ezradio_func_info (ezradio_cmd_reply_t * ezradioReply)
Sends the FUNC_INFO command to the radio, then reads the resonse into ezradioReply union.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 415 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_adc_reading (uint8_t adc_en, uint8_t adc_cfg, ezradio_cmd_reply_t * ezradioReply)
Reads the ADC values from the radio into ezradioReply union.
Parameters:
[in] adc_en ADC enable parameter.
[in] adc_cfg ADC configuration parameter.
[out] ezradioReply Reply structure of the command.
Definition at line 192 of file ezradio_api_lib_add.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_chip_status (uint8_t chip_clr_pend, ezradio_cmd_reply_t * ezradioReply)
Gets the Chip status flags.
Optionally clears them.
Parameters:
[in] chip_clr_pend Flags to clear.
[out] ezradioReply Reply structure of the command.
Definition at line 635 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_chip_status_fast_clear (void)
Clear all Chip status flags.
Does NOT read back interrupt flags
Definition at line 868 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_get_chip_status_fast_clear_read (ezradio_cmd_reply_t * ezradioReply)
Clear and read all Chip status flags.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 884 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_int_status (uint8_t ph_clr_pend, uint8_t modem_clr_pend, uint8_t chip_clr_pend, ezradio_cmd_reply_t * ezradioReply)
Get the Interrupt status/pending flags form the radio and clear flags if requested.
Parameters:
[in] ph_clr_pend Packet Handler pending flags clear.
[in] modem_clr_pend Modem Status pending flags clear.
[in] chip_clr_pend Chip State pending flags clear.
[out] ezradioReply Reply structure of the command.
Definition at line 181 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
Referenced by ezradio_configuration_init(), ezradioInit(), ezradioPluginManager(), ezradioStartDirectReceive(), ezradioStartDirectTransmit(), ezradioStartPn9(), and ezradioStartUnmodulatedCarrier().
void ezradio_get_int_status_fast_clear (void)
Clear all Interrupt status/pending flags.
Does NOT read back interrupt flags
Definition at line 722 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_get_int_status_fast_clear_read (ezradio_cmd_reply_t * ezradioReply)
Clear and read all Interrupt status/pending flags.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 737 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_modem_status (uint8_t modem_clr_pend, ezradio_cmd_reply_t * ezradioReply)
Gets the Modem status flags.
Optionally clears them.
Parameters:
[in] modem_clr_pend Flags to clear.
[out] ezradioReply Reply structure of the command.
Definition at line 606 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_modem_status_fast_clear (void)
Clear all Modem status flags.
Does NOT read back interrupt flags
Definition at line 826 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_get_modem_status_fast_clear_read (ezradio_cmd_reply_t * ezradioReply)
Clear and read all Modem status flags.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 842 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_packet_info (uint8_t field_number_mask, uint16_t len, int16_t diff_len, ezradio_cmd_reply_t * ezradioReply)
Receives information from the radio of the current packet.
Optionally can be used to modify the Packet Handler properties during packet reception.
Parameters:
[in] field_number_mask Packet Field number mask value.
[in] len Length value.
[in] diff_len Difference length.
[out] ezradioReply Reply structure of the command.
Definition at line 663 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_ph_status (uint8_t ph_clr_pend, ezradio_cmd_reply_t * ezradioReply)
Gets the Packet Handler status flags.
Optionally clears them.
Parameters:
[in] ph_clr_pend Flags to clear.
[out] ezradioReply Reply structure of the command.
Definition at line 583 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_ph_status_fast_clear (void)
Clear all Packet Handler status flags.
Does NOT read back interrupt flags
Definition at line 790 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_get_ph_status_fast_clear_read (ezradio_cmd_reply_t * ezradioReply)
Clear and read all Packet Handler status flags.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 806 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_get_property (uint8_t group, uint8_t num_props, uint8_t start_prop, ezradio_cmd_reply_t * ezradioReply)
Get property values from the radio.
Reads them into ezradioReply union.
Parameters:
[in] group Property group number.
[in] num_props Number of properties to be read.
[in] start_prop Starting sub-property number.
[out] ezradioReply Reply structure of the command.
Definition at line 373 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_gpio_pin_cfg (uint8_t gpio0, uint8_t gpio1, uint8_t gpio2, uint8_t gpio3, uint8_t nirq, uint8_t sdo, uint8_t gen_config, ezradio_cmd_reply_t * ezradioReply)
Send GPIO pin config command to the radio and reads the answer into ezradioReply union.
Parameters:
[in] gpio0 GPIO0 configuration.
[in] gpio1 GPIO1 configuration.
[in] gpio2 GPIO2 configuration.
[in] gpio3 GPIO3 configuration.
[in] nirq NIRQ configuration.
[in] sdo SDO configuration.
[in] gen_config General pin configuration.
[out] ezradioReply Reply structure of the command.
Definition at line 220 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_gpio_pin_cfg_fast (ezradio_cmd_reply_t * ezradioReply)
Reads back current GPIO pin configuration.
Does NOT configure GPIO pins
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 764 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_ircal (uint8_t searching_step_size, uint8_t searching_rssi_avg, uint8_t rx_chain_setting1, uint8_t rx_chain_setting2)
Performs image rejection calibration.
Completion can be monitored by polling CTS or waiting for CHIP_READY interrupt source.
Parameters:
[in] searching_step_size
[in] searching_rssi_avg
[in] rx_chain_setting1
[in] rx_chain_setting2
Definition at line 147 of file ezradio_api_lib_add.c.
References ezradio_comm_SendCmd().
void ezradio_ircal_manual (uint8_t ircal_amp, uint8_t ircal_ph, ezradio_cmd_reply_t * ezradioReply)
Image rejection calibration.
Forces a specific value for IR calibration, and reads back calibration values from previous calibrations
Parameters:
[in] ircal_amp
[in] ircal_ph
[out] ezradioReply Reply structure of the command.
Definition at line 168 of file ezradio_api_lib_add.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_nop (void)
Sends NOP command to the radio.
Can be used to maintain SPI communication.
Definition at line 308 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_part_info (ezradio_cmd_reply_t * ezradioReply)
This function sends the PART_INFO command to the radio and receives the answer into ezradioReply union.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 100 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_power_up (uint8_t boot_options, uint8_t xtal_options, uint32_t xo_freq)
This function is used to initialize after power-up the radio chip.
Before this function ezradio_reset should be called.
Parameters:
[in] boot_options Boot options input to the power up command.
[in] xtal_options XTAL options input to the power up command.
[in] xo_freq XO frequency input to the power up command.
Definition at line 79 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_read_cmd_buff (ezradio_cmd_reply_t * ezradioReply)
Reads the command buffer.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 547 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
void ezradio_read_rx_fifo (uint8_t numBytes, uint8_t * pRxData)
Reads the RX FIFO content from the radio.
Parameters:
[in] numBytes Data length to be read.
[in] pRxData Pointer to the buffer location.
Definition at line 360 of file ezradio_api_lib.c.
References ezradio_comm_ReadData().
void ezradio_request_device_state (ezradio_cmd_reply_t * ezradioReply)
Requests the current state of the device and lists pending TX and RX requests.
Parameters:
[out] ezradioReply Reply structure of the command.
Definition at line 526 of file ezradio_api_lib.c.
References ezradio_comm_SendCmdGetResp().
Referenced by ezradioStartDirectTransmit(), ezradioStartPn9(), and ezradioStartUnmodulatedCarrier().
void ezradio_reset (void)
This functions is used to reset the EZRadio device by applying shutdown and releasing it.
After this function ezradio_power_up or ezradio_configuration_init should be called. The user can check if POR has completed by waiting 4 ms or by polling radio GPIO 0, 2, or 3. When these GPIOs are high, it is safe to call the above mentioned functions.
Definition at line 53 of file ezradio_api_lib.c.
References ezradio_comm_ClearCTS(), ezradio_hal_AssertShutdown(), ezradio_hal_DeassertShutdown(), USTIMER_DeInit(), USTIMER_Delay(), and USTIMER_Init().
void ezradio_rx_hop (uint8_t inte, uint8_t frac2, uint8_t frac1, uint8_t frac0, uint8_t vco_cnt1, uint8_t vco_cnt0)
While in RX state this will hop to the frequency specified by the parameters and start searching for a preamble.
Parameters:
[in] inte new inte register value.
[in] frac2 new frac2 register value.
[in] frac1 new frac1 register value.
[in] frac0 new frac0 register value.
[in] vco_cnt1 new vco_cnt1 register value.
[in] vco_cnt0 new vco_cnt0 register value.
Definition at line 226 of file ezradio_api_lib_add.c.
References ezradio_comm_SendCmd().
void ezradio_set_property (uint8_t group, uint8_t num_props, uint8_t start_prop, ...)
Send SET_PROPERTY command to the radio.
Parameters:
[in] group Property group.
[in] num_props Number of property to be set. The properties must be in ascending order in their sub-property aspect. Max. 12 properties can be set in one command.
[in] start_prop Start sub-property address.
[in] ... Variable number of properties to be set.
Definition at line 261 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_start_rx (uint8_t channel, uint8_t condition, uint16_t rx_len, uint8_t next_state1, uint8_t next_state2, uint8_t next_state3)
Sends START_RX command to the radio.
Parameters:
[in] channel Channel number.
[in] condition Start RX condition.
[in] rx_len Payload length (exclude the PH generated CRC).
[in] next_state1 Next state when Preamble Timeout occurs.
[in] next_state2 Next state when a valid packet received.
[in] next_state3 Next state when invalid packet received (e.g. CRC error).
Definition at line 156 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
Referenced by ezradioStartDirectReceive(), and ezradioStartRx().
void ezradio_start_rx_fast (void)
Sends START_RX command ID to the radio with no input parameters.
Definition at line 708 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_start_tx (uint8_t channel, uint8_t condition, uint16_t tx_len)
Sends START_TX command to the radio.
Parameters:
[in] channel Channel number.
[in] condition Start TX condition.
[in] tx_len Payload length (exclude the PH generated CRC).
Definition at line 127 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
Referenced by ezradioStartDirectTransmit(), ezradioStartPn9(), and ezradioStartUnmodulatedCarrier().
void ezradio_start_tx_fast (void)
Sends START_TX command ID to the radio with no input parameters.
Definition at line 694 of file ezradio_api_lib.c.
References ezradio_comm_SendCmd().
void ezradio_tx_hop (uint8_t inte, uint8_t frac2, uint8_t frac1, uint8_t frac0, uint8_t vco_cnt1, uint8_t vco_cnt0, uint8_t pll_settle_time1, uint8_t pll_settle_time0)
While in TX state this will hop to the frequency specified by the parameters.
Parameters:
[in] inte new inte register value.
[in] frac2 new frac2 register value.
[in] frac1 new frac1 register value.
[in] frac0 new frac0 register value.
[in] vco_cnt1 new vco_cnt1 register value.
[in] vco_cnt0 new vco_cnt0 register value.
[in] pll_settle_time1 new pll_settle_time1 register value.
[in] pll_settle_time0 new pll_settle_time0 register value.
Definition at line 198 of file ezradio_api_lib_add.c.
References ezradio_comm_SendCmd().
void ezradio_write_ezconfig_array (uint8_t numBytes, uint8_t * pEzConfigArray)
Writes data byte(s) to the EZConfig array.
Parameters:
[in] numBytes number of bytes to send
[in] pEzConfigArray pointer to the EZConfig configuration array
Definition at line 147 of file ezradio_api_lib_add.c.
References ezradio_comm_WriteData().
Referenced by ezradio_configuration_init().
void ezradio_write_tx_fifo (uint8_t numBytes, uint8_t * pTxData)
The function can be used to load data into TX FIFO.
Parameters:
[in] numBytes Data length to be load.
[in] pTxData Pointer to the data (uint8_t*).
Definition at line 349 of file ezradio_api_lib.c.
References ezradio_comm_WriteData().