Silicon Labs Energy Aware Drivers: COMM_Layer
COMM_Layer
[EZRADIODRV]
EzRadio Communication Layer, see Communication Layer on page EZRADIODRV EzRadio Peripheral Interface driver for detailed documentation.
Defines
#define EZRADIO_CTS_TIMEOUT 10000
Radio CTS timeout.
Functions
uint8_t ezradio_comm_GetResp (uint8_t byteCount, uint8_t *pData)
Gets a command response from the radio chip.
void ezradio_comm_SendCmd (uint8_t byteCount, uint8_t *pData)
Sends a command to the radio chip.
void ezradio_comm_ReadData (uint8_t cmd, uint8_t pollCts, uint8_t byteCount, uint8_t *pData)
Gets a command response from the radio chip.
void ezradio_comm_WriteData (uint8_t cmd, uint8_t pollCts, uint8_t byteCount, uint8_t *pData)
Gets a command response from the radio chip.
uint8_t ezradio_comm_PollCTS (void)
Waits for CTS to be high.
uint8_t ezradio_comm_SendCmdGetResp (uint8_t cmdByteCount, uint8_t *pCmdData, uint8_t respByteCount, uint8_t *pRespData)
Sends a command to the radio chip and gets a response.
void ezradio_comm_ClearCTS (void)
Clears the CTS state variable.
Variables
uint8_t ezradio_comm_CtsWentHigh
Can be used to prevent CTS check before any communication command.
Detailed Description
EzRadio Communication Layer, see Communication Layer on page EZRADIODRV EzRadio Peripheral Interface driver for detailed documentation.
Define Documentation
#define EZRADIO_CTS_TIMEOUT 10000
Radio CTS timeout.
Definition at line 58 of file ezradio_comm.h.
Referenced by ezradio_comm_GetResp().
Function Documentation
void ezradio_comm_ClearCTS (void)
Clears the CTS state variable.
Definition at line 183 of file ezradio_comm.c.
References ezradio_comm_CtsWentHigh.
Referenced by ezradio_reset().
uint8_t ezradio_comm_GetResp (uint8_t byteCount, uint8_t * pData)
Gets a command response from the radio chip.
Parameters:
byteCount Number of bytes to get from the radio chip
pData Pointer to where to put the data
Returns:
CTS value
Definition at line 52 of file ezradio_comm.c.
References ezradio_comm_CtsWentHigh, EZRADIO_CTS_TIMEOUT, ezradio_hal_ClearNsel(), ezradio_hal_SetNsel(), ezradio_hal_SpiReadByte(), ezradio_hal_SpiReadData(), and ezradio_hal_SpiWriteByte().
Referenced by ezradio_comm_PollCTS(), and ezradio_comm_SendCmdGetResp().
uint8_t ezradio_comm_PollCTS (void)
Waits for CTS to be high.
Returns:
CTS value
Definition at line 166 of file ezradio_comm.c.
References ezradio_comm_CtsWentHigh, and ezradio_comm_GetResp().
Referenced by ezradio_comm_ReadData(), ezradio_comm_SendCmd(), and ezradio_comm_WriteData().
void ezradio_comm_ReadData (uint8_t cmd, uint8_t pollCts, uint8_t byteCount, uint8_t * pData)
Gets a command response from the radio chip.
Parameters:
cmd Command ID
pollCts Set to poll CTS
byteCount Number of bytes to get from the radio chip.
pData Pointer to where to put the data.
Definition at line 120 of file ezradio_comm.c.
References ezradio_comm_CtsWentHigh, ezradio_comm_PollCTS(), ezradio_hal_ClearNsel(), ezradio_hal_SetNsel(), ezradio_hal_SpiReadData(), and ezradio_hal_SpiWriteByte().
Referenced by ezradio_frr_a_read(), ezradio_frr_b_read(), ezradio_frr_c_read(), ezradio_frr_d_read(), and ezradio_read_rx_fifo().
void ezradio_comm_SendCmd (uint8_t byteCount, uint8_t * pData)
Sends a command to the radio chip.
Parameters:
byteCount Number of bytes in the command to send to the radio device
pData Pointer to the command to send.
Definition at line 100 of file ezradio_comm.c.
References ezradio_comm_CtsWentHigh, ezradio_comm_PollCTS(), ezradio_hal_ClearNsel(), ezradio_hal_SetNsel(), and ezradio_hal_SpiWriteData().
Referenced by ezradio_change_state(), ezradio_comm_SendCmdGetResp(), ezradio_fifo_info_fast_reset(), ezradio_get_chip_status_fast_clear(), ezradio_get_int_status_fast_clear(), ezradio_get_modem_status_fast_clear(), ezradio_get_ph_status_fast_clear(), ezradio_ircal(), ezradio_nop(), ezradio_power_up(), ezradio_rx_hop(), ezradio_set_property(), ezradio_start_rx(), ezradio_start_rx_fast(), ezradio_start_tx(), ezradio_start_tx_fast(), and ezradio_tx_hop().
uint8_t ezradio_comm_SendCmdGetResp (uint8_t cmdByteCount, uint8_t * pCmdData, uint8_t respByteCount, uint8_t * pRespData)
Sends a command to the radio chip and gets a response.
Parameters:
cmdByteCount Number of bytes in the command to send to the radio device
pCmdData Pointer to the command data
respByteCount Number of bytes in the response to fetch
pRespData Pointer to where to put the response data
Returns:
CTS value
Definition at line 198 of file ezradio_comm.c.
References ezradio_comm_GetResp(), and ezradio_comm_SendCmd().
Referenced by ezradio_configuration_init(), ezradio_ezconfig_check(), ezradio_fifo_info(), ezradio_fifo_info_fast_read(), ezradio_func_info(), ezradio_get_adc_reading(), ezradio_get_chip_status(), ezradio_get_chip_status_fast_clear_read(), ezradio_get_int_status(), ezradio_get_int_status_fast_clear_read(), ezradio_get_modem_status(), ezradio_get_modem_status_fast_clear_read(), ezradio_get_packet_info(), ezradio_get_ph_status(), ezradio_get_ph_status_fast_clear_read(), ezradio_get_property(), ezradio_gpio_pin_cfg(), ezradio_gpio_pin_cfg_fast(), ezradio_ircal_manual(), ezradio_part_info(), ezradio_read_cmd_buff(), and ezradio_request_device_state().
void ezradio_comm_WriteData (uint8_t cmd, uint8_t pollCts, uint8_t byteCount, uint8_t * pData)
Gets a command response from the radio chip.
Parameters:
cmd Command ID
pollCts Set to poll CTS
byteCount Number of bytes to get from the radio chip
pData Pointer to where to put the data
Definition at line 145 of file ezradio_comm.c.
References ezradio_comm_CtsWentHigh, ezradio_comm_PollCTS(), ezradio_hal_ClearNsel(), ezradio_hal_SetNsel(), ezradio_hal_SpiWriteByte(), and ezradio_hal_SpiWriteData().
Referenced by ezradio_write_ezconfig_array(), and ezradio_write_tx_fifo().
Variable Documentation
uint8_t ezradio_comm_CtsWentHigh
Can be used to prevent CTS check before any communication command.
Definition at line 42 of file ezradio_comm.c.
Referenced by ezradio_comm_ClearCTS(), ezradio_comm_GetResp(), ezradio_comm_PollCTS(), ezradio_comm_ReadData(), ezradio_comm_SendCmd(), ezradio_comm_WriteData(), and ezradio_ezconfig_check().