@echo off

REM This file was generated by Simplicity Studio from the following template:
REM   app/esf_common/template/efr32/efr32-prebuild.bat
REM Please do not edit it directly.

REM Pre Build processing for IAR Workbench.
