Silicon Labs EFM32 emlib Peripheral Library: RMU
RMU
[EM_Library]
Reset Management Unit (RMU) Peripheral API.
Defines
#define RMU_LockupResetDisable(A) RMU_ResetControl(rmuResetLockUp, A)
Enumerations
enum RMU_Reset_TypeDef { rmuResetLockUp = _RMU_CTRL_LOCKUPRDIS_SHIFT }
Functions
void RMU_ResetControl (RMU_Reset_TypeDef reset, bool enable)
Disable/enable reset for various peripherals and signal sources.
void RMU_ResetCauseClear (void)
Clear the reset cause register.
uint32_t RMU_ResetCauseGet (void)
Get the cause of the last reset.
Detailed Description
Reset Management Unit (RMU) Peripheral API.
Define Documentation
#define RMU_LockupResetDisable (A) RMU_ResetControl(rmuResetLockUp, A)
RMU_LockupResetDisable kept for backwards compatibility
Definition at line 76 of file em_rmu.h.
Enumeration Type Documentation
enum RMU_Reset_TypeDef
RMU controlled peripheral reset control and reset source control
Enumerator:
rmuResetLockUp
Allow Cortex-M3 lock up signal
Definition at line 61 of file em_rmu.h.
Function Documentation
void RMU_ResetCauseClear (void)
Clear the reset cause register.
This function clears all the reset cause bits of the RSTCAUSE register. The reset cause bits must be cleared by SW before a new reset occurs, otherwise reset causes may accumulate. See RMU_ResetCauseGet().
Definition at line 169 of file em_rmu.c.
References BITBAND_Peripheral(), EMU_Lock(), and EMU_Unlock().
uint32_t RMU_ResetCauseGet (void)
Get the cause of the last reset.
In order to be useful, the reset cause must be cleared by SW before a new reset occurs, otherwise reset causes may accumulate. See RMU_ResetCauseClear(). This function call will return the main cause for reset, which can be a bit mask (several causes), and clear away "noise".
Returns:
The reset cause, a bit mask of (typically, but not always, only one) of:
RMU_RSTCAUSE_PORST - Power on reset
RMU_RSTCAUSE_BODUNREGRST - Brown out detector, unregulated power
RMU_RSTCAUSE_BODREGRST - Brown out detector, regulated power
RMU_RSTCAUSE_EXTRST - External reset
RMU_RSTCAUSE_WDOGRST - Watchdog reset
RMU_RSTCAUSE_LOCKUPRST - Cortex-M3 lockup reset
RMU_RSTCAUSE_SYSREQRST - Cortex-M3 system request reset
RMU_RSTCAUSE_EM4RST - Set if the system has been in EM4
RMU_RSTCAUSE_EM4WURST - Set if the system woke up on a pin from EM4
RMU_RSTCAUSE_BODAVDD0 - Analog power domain 0 brown out detector reset
RMU_RSTCAUSE_BODAVDD1 - Analog power domain 1 brown out detector reset
RMU_RSTCAUSE_BUBODVDDDREG - Backup BOD on VDDD_REG triggered
RMU_RSTCAUSE_BUBODBUVIN - Backup BOD on BU_VIN triggered
RMU_RSTCAUSE_BUBODUNREG - Backup BOD on unregulated power triggered
RMU_RSTCAUSE_BUBODREG - Backup BOD on regulated powered has triggered
RMU_RSTCAUSE_BUMODERST - System has been in Backup mode
Definition at line 222 of file em_rmu.c.
void RMU_ResetControl (RMU_Reset_TypeDef reset, bool enable)
Disable/enable reset for various peripherals and signal sources.
Parameters:
[in] reset Reset types to enable/disable
[in] enable
false - Disable reset signal or flag
true - Enable reset signal or flag
Definition at line 154 of file em_rmu.c.
References BITBAND_Peripheral().