var group__Parts =
[
    [ "EFM32G890F128", "group__EFM32G890F128.html", "group__EFM32G890F128" ],
    [ "EFM32G_ACMP", "group__EFM32G__ACMP.html", "group__EFM32G__ACMP" ],
    [ "EFM32G_ACMP_BitFields", "group__EFM32G__ACMP__BitFields.html", "group__EFM32G__ACMP__BitFields" ],
    [ "EFM32G_ADC", "group__EFM32G__ADC.html", "group__EFM32G__ADC" ],
    [ "EFM32G_ADC_BitFields", "group__EFM32G__ADC__BitFields.html", "group__EFM32G__ADC__BitFields" ],
    [ "EFM32G_AES", "group__EFM32G__AES.html", "group__EFM32G__AES" ],
    [ "EFM32G_AES_BitFields", "group__EFM32G__AES__BitFields.html", "group__EFM32G__AES__BitFields" ],
    [ "EFM32G_AF_Pins", "group__EFM32G__AF__Pins.html", "group__EFM32G__AF__Pins" ],
    [ "EFM32G_AF_Ports", "group__EFM32G__AF__Ports.html", "group__EFM32G__AF__Ports" ],
    [ "EFM32G_CALIBRATE", "group__EFM32G__CALIBRATE.html", "group__EFM32G__CALIBRATE" ],
    [ "EFM32G_CMU", "group__EFM32G__CMU.html", "group__EFM32G__CMU" ],
    [ "EFM32G_CMU_BitFields", "group__EFM32G__CMU__BitFields.html", "group__EFM32G__CMU__BitFields" ],
    [ "EFM32G_DAC", "group__EFM32G__DAC.html", "group__EFM32G__DAC" ],
    [ "EFM32G_DAC_BitFields", "group__EFM32G__DAC__BitFields.html", "group__EFM32G__DAC__BitFields" ],
    [ "EFM32G_DEVINFO", "group__EFM32G__DEVINFO.html", "group__EFM32G__DEVINFO" ],
    [ "EFM32G_DEVINFO_BitFields", "group__EFM32G__DEVINFO__BitFields.html", "group__EFM32G__DEVINFO__BitFields" ],
    [ "EFM32G_DMA", "group__EFM32G__DMA.html", "group__EFM32G__DMA" ],
    [ "EFM32G_DMA_BitFields", "group__EFM32G__DMA__BitFields.html", "group__EFM32G__DMA__BitFields" ],
    [ "EFM32G_DMACTRL_BitFields", "group__EFM32G__DMACTRL__BitFields.html", "group__EFM32G__DMACTRL__BitFields" ],
    [ "EFM32G_DMAREQ_BitFields", "group__EFM32G__DMAREQ__BitFields.html", "group__EFM32G__DMAREQ__BitFields" ],
    [ "EFM32G_DMA_DESCRIPTOR", "group__EFM32G__DMA__DESCRIPTOR.html", "group__EFM32G__DMA__DESCRIPTOR" ],
    [ "EFM32G_EBI", "group__EFM32G__EBI.html", "group__EFM32G__EBI" ],
    [ "EFM32G_EBI_BitFields", "group__EFM32G__EBI__BitFields.html", "group__EFM32G__EBI__BitFields" ],
    [ "EFM32G_EMU", "group__EFM32G__EMU.html", "group__EFM32G__EMU" ],
    [ "EFM32G_EMU_BitFields", "group__EFM32G__EMU__BitFields.html", "group__EFM32G__EMU__BitFields" ],
    [ "EFM32G_GPIO", "group__EFM32G__GPIO.html", "group__EFM32G__GPIO" ],
    [ "EFM32G_GPIO_BitFields", "group__EFM32G__GPIO__BitFields.html", "group__EFM32G__GPIO__BitFields" ],
    [ "EFM32G_I2C", "group__EFM32G__I2C.html", "group__EFM32G__I2C" ],
    [ "EFM32G_I2C_BitFields", "group__EFM32G__I2C__BitFields.html", "group__EFM32G__I2C__BitFields" ],
    [ "EFM32G_LCD", "group__EFM32G__LCD.html", "group__EFM32G__LCD" ],
    [ "EFM32G_LCD_BitFields", "group__EFM32G__LCD__BitFields.html", "group__EFM32G__LCD__BitFields" ],
    [ "EFM32G_LETIMER", "group__EFM32G__LETIMER.html", "group__EFM32G__LETIMER" ],
    [ "EFM32G_LETIMER_BitFields", "group__EFM32G__LETIMER__BitFields.html", "group__EFM32G__LETIMER__BitFields" ],
    [ "EFM32G_LEUART", "group__EFM32G__LEUART.html", "group__EFM32G__LEUART" ],
    [ "EFM32G_LEUART_BitFields", "group__EFM32G__LEUART__BitFields.html", "group__EFM32G__LEUART__BitFields" ],
    [ "EFM32G_MSC", "group__EFM32G__MSC.html", "group__EFM32G__MSC" ],
    [ "EFM32G_MSC_BitFields", "group__EFM32G__MSC__BitFields.html", "group__EFM32G__MSC__BitFields" ],
    [ "EFM32G_PCNT", "group__EFM32G__PCNT.html", "group__EFM32G__PCNT" ],
    [ "EFM32G_PCNT_BitFields", "group__EFM32G__PCNT__BitFields.html", "group__EFM32G__PCNT__BitFields" ],
    [ "EFM32G_PRS", "group__EFM32G__PRS.html", "group__EFM32G__PRS" ],
    [ "EFM32G_PRS_BitFields", "group__EFM32G__PRS__BitFields.html", "group__EFM32G__PRS__BitFields" ],
    [ "EFM32G_RMU", "group__EFM32G__RMU.html", "group__EFM32G__RMU" ],
    [ "EFM32G_RMU_BitFields", "group__EFM32G__RMU__BitFields.html", "group__EFM32G__RMU__BitFields" ],
    [ "EFM32G_ROMTABLE", "group__EFM32G__ROMTABLE.html", "group__EFM32G__ROMTABLE" ],
    [ "EFM32G_ROMTABLE_BitFields", "group__EFM32G__ROMTABLE__BitFields.html", "group__EFM32G__ROMTABLE__BitFields" ],
    [ "EFM32G_RTC", "group__EFM32G__RTC.html", "group__EFM32G__RTC" ],
    [ "EFM32G_RTC_BitFields", "group__EFM32G__RTC__BitFields.html", "group__EFM32G__RTC__BitFields" ],
    [ "EFM32G_TIMER", "group__EFM32G__TIMER.html", "group__EFM32G__TIMER" ],
    [ "EFM32G_TIMER_BitFields", "group__EFM32G__TIMER__BitFields.html", "group__EFM32G__TIMER__BitFields" ],
    [ "EFM32G_UART_BitFields", "group__EFM32G__UART__BitFields.html", "group__EFM32G__UART__BitFields" ],
    [ "EFM32G_USART", "group__EFM32G__USART.html", "group__EFM32G__USART" ],
    [ "EFM32G_USART_BitFields", "group__EFM32G__USART__BitFields.html", "group__EFM32G__USART__BitFields" ],
    [ "EFM32G_VCMP", "group__EFM32G__VCMP.html", "group__EFM32G__VCMP" ],
    [ "EFM32G_VCMP_BitFields", "group__EFM32G__VCMP__BitFields.html", "group__EFM32G__VCMP__BitFields" ],
    [ "EFM32G_WDOG", "group__EFM32G__WDOG.html", "group__EFM32G__WDOG" ],
    [ "EFM32G_WDOG_BitFields", "group__EFM32G__WDOG__BitFields.html", "group__EFM32G__WDOG__BitFields" ],
    [ "EFM32G_PRS_Signals", "group__EFM32G__PRS__Signals.html", "group__EFM32G__PRS__Signals" ],
    [ "DMA_CH_TypeDef", "structDMA__CH__TypeDef.html", [
      [ "CTRL", "structDMA__CH__TypeDef.html#a266a6da8822d29e619c942e30f217de7", null ]
    ] ],
    [ "GPIO_P_TypeDef", "structGPIO__P__TypeDef.html", [
      [ "CTRL", "structGPIO__P__TypeDef.html#a5b0ed681dcf52fefe424c3145cd5025f", null ],
      [ "MODEL", "structGPIO__P__TypeDef.html#ad28242da58dcd7bf160cfdee1abe70d2", null ],
      [ "MODEH", "structGPIO__P__TypeDef.html#aa8a7ce592d8fa594a61cf37d62c1d7d4", null ],
      [ "DOUT", "structGPIO__P__TypeDef.html#a042c3a572e749f67f63d9a094e96d567", null ],
      [ "DOUTSET", "structGPIO__P__TypeDef.html#a0d8f76be5706698e8e3fee8438c90b6a", null ],
      [ "DOUTCLR", "structGPIO__P__TypeDef.html#aa4fc7332bb9352c0cbe1f05b64ca370a", null ],
      [ "DOUTTGL", "structGPIO__P__TypeDef.html#a576341b58cbf31bfc9552f29c0276bca", null ],
      [ "DIN", "structGPIO__P__TypeDef.html#a32cb3813b6bf7534d6e640528741a82e", null ],
      [ "PINLOCKN", "structGPIO__P__TypeDef.html#a8858ff71b6607d96c82d221841686d0d", null ]
    ] ],
    [ "PRS_CH_TypeDef", "structPRS__CH__TypeDef.html", [
      [ "CTRL", "structPRS__CH__TypeDef.html#a44f30addd8273511c81d535fef2414b2", null ]
    ] ],
    [ "TIMER_CC_TypeDef", "structTIMER__CC__TypeDef.html", [
      [ "CTRL", "structTIMER__CC__TypeDef.html#af3a7a604528309ce227e5a048f61e770", null ],
      [ "CCV", "structTIMER__CC__TypeDef.html#acc9438c0f8107f2ad9e358c8afb73bf2", null ],
      [ "CCVP", "structTIMER__CC__TypeDef.html#a1673fb669a6ae2f7081d9a5f3f294785", null ],
      [ "CCVB", "structTIMER__CC__TypeDef.html#aa3eff4dcde68225978411d7419aa81a9", null ]
    ] ]
];