EFM32 Gecko Software Documentation: VddCheck
VddCheck
Drivers
Functions
void VDDCHECK_Init (void)
VCMP initialization routine.
void VDDCHECK_Disable (void)
VCMP deinitialization routine.
bool VDDCHECK_LowVoltage (float vdd)
Check if voltage is higher than indicated.
Detailed Description
Function Documentation
bool VDDCHECK_LowVoltage (float vdd)
Parameters
vdd The voltage level to compare against.
Returns
Returns true if voltage is lower, false otherwise
Definition at line 55 of file vddcheck.c.
References VCMP_Init_TypeDef::enable, VCMP_Init_TypeDef::lowPowerRef, VCMP_Init_TypeDef::triggerLevel, VCMP_Init(), VCMP_INIT_DEFAULT, VCMP_Ready(), VCMP_VDDHigher(), VCMP_VoltageToLevel(), vcmpWarmTime128Cycles, and VCMP_Init_TypeDef::warmup.